services:
  voice-relay:
    container_name: voice-relay
    image: voice-relay:latest
    pull_policy: never
    env_file:
      - .env
    ports:
      - "${PORT:-9000}:${PORT:-9000}"
    volumes:
      - ./sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01:/app/sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01:ro
      - ./keywords.txt:/app/keywords.txt:ro
    restart: unless-stopped
